import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

import fs from "fs";
import path from "path";

const outdirs = [
	"test-vault/.obsidian/plugins/obsidian-agentic-vault",
	"test-vaults/test-vault-empty/.obsidian/plugins/obsidian-agentic-vault"
];
const copyPlugin = {
	name: "copy-plugin",
	setup(build) {
		build.onEnd(() => {
			for (const dir of outdirs) {
				try {
					fs.mkdirSync(dir, { recursive: true });
					fs.copyFileSync("main.js", path.join(dir, "main.js"));
					fs.copyFileSync("manifest.json", path.join(dir, "manifest.json"));
					if (fs.existsSync("styles.css")) {
						fs.copyFileSync("styles.css", path.join(dir, "styles.css"));
					}
				} catch (e) {
					console.warn("Failed to copy to " + dir, e);
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map(m => "node:" + m)
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
