import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

import fs from "fs";
import path from "path";

const outdir = "test-vault/.obsidian/plugins/obsidian-agentic-vault";
const copyPlugin = {
	name: "copy-plugin",
	setup(build) {
		build.onEnd(() => {
			fs.mkdirSync(outdir, { recursive: true });
			fs.copyFileSync("main.js", path.join(outdir, "main.js"));
			fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
			if (fs.existsSync("styles.css")) {
				fs.copyFileSync("styles.css", path.join(outdir, "styles.css"));
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map(m => "node:" + m)
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
