import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const fleetsDir = path.join(__dirname, '../src/fleets');
const outputFile = path.join(__dirname, '../src/blueprints/BundledFleets.ts');

function walkDir(dir) {
    let results = [];
    const list = fs.readdirSync(dir);
    list.forEach(file => {
        file = path.join(dir, file);
        const stat = fs.statSync(file);
        if (stat && stat.isDirectory()) {
            results = results.concat(walkDir(file));
        } else {
            if (file.endsWith('.md')) {
                results.push(file);
            }
        }
    });
    return results;
}

const bundledFleets = {};

if (fs.existsSync(fleetsDir)) {
    const fleets = fs.readdirSync(fleetsDir).filter(f => fs.statSync(path.join(fleetsDir, f)).isDirectory());

    for (const fleet of fleets) {
        bundledFleets[fleet] = {
            name: fleet,
            files: {
                personas: [],
                tools: [],
                skills: [],
                routines: [],
                templates: [],
                root: []
            }
        };

        const fleetPath = path.join(fleetsDir, fleet);
        const files = walkDir(fleetPath);

        for (const file of files) {
            const relPath = path.relative(fleetPath, file);
            const content = fs.readFileSync(file, 'utf-8');
            
            const parts = relPath.split(path.sep);
            const filename = parts.pop();
            const category = parts[0];

            const fileObj = { filename, content };

            if (category === 'personas') bundledFleets[fleet].files.personas.push(fileObj);
            else if (category === 'tools') bundledFleets[fleet].files.tools.push(fileObj);
            else if (category === 'skills') bundledFleets[fleet].files.skills.push(fileObj);
            else if (category === 'routines') bundledFleets[fleet].files.routines.push(fileObj);
            else if (category === 'templates') bundledFleets[fleet].files.templates.push(fileObj);
            else bundledFleets[fleet].files.root.push({ filename: relPath, content });
        }
    }
}

const tsContent = `// AUTO-GENERATED BY scripts/pack-fleets.mjs
// DO NOT EDIT DIRECTLY

export interface BundledFile {
    filename: string;
    content: string;
}

export interface BundledFleet {
    name: string;
    files: {
        personas: BundledFile[];
        tools: BundledFile[];
        skills: BundledFile[];
        routines: BundledFile[];
        templates: BundledFile[];
        root: BundledFile[];
    }
}

export const BundledFleets: Record<string, BundledFleet> = ${JSON.stringify(bundledFleets, null, 4)};
`;

fs.writeFileSync(outputFile, tsContent);
console.log('Successfully packed fleets into src/blueprints/BundledFleets.ts');
